name: pro_video_player
description: Premium glassmorphic video player with iOS features.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  
  # Media Player Engine
  media_kit: ^1.1.11
  media_kit_video: ^1.2.4
  media_kit_libs_video: ^1.0.7
  
  # Core Utility Packages
  permission_handler: ^11.3.1
  path: ^1.9.0
  device_info_plus: ^10.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
